// Code generated by hand to match mockery v2.53.2 conventions (mockery's
// embedded go1.24 parser cannot load this go1.25 module). DO NOT EDIT by hand
// without keeping every method in sync with the interface.

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	entities "go-trade-bot/app/entities"
	agentplatform "go-trade-bot/app/repository/agentplatform"
)

// Repository is a mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateAgent provides a mock function
func (_m *Repository) CreateAgent(ctx context.Context, a entities.Agent) (entities.Agent, error) {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for CreateAgent")
	}

	var r0 entities.Agent
	if rf, ok := ret.Get(0).(func(context.Context, entities.Agent) entities.Agent); ok {
		r0 = rf(ctx, a)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(entities.Agent)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// UpdateAgent provides a mock function
func (_m *Repository) UpdateAgent(ctx context.Context, a entities.Agent) (entities.Agent, error) {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAgent")
	}

	var r0 entities.Agent
	if rf, ok := ret.Get(0).(func(context.Context, entities.Agent) entities.Agent); ok {
		r0 = rf(ctx, a)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(entities.Agent)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// GetAgent provides a mock function
func (_m *Repository) GetAgent(ctx context.Context, id uint) (entities.Agent, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAgent")
	}

	var r0 entities.Agent
	if rf, ok := ret.Get(0).(func(context.Context, uint) entities.Agent); ok {
		r0 = rf(ctx, id)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(entities.Agent)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// GetAgentByName provides a mock function
func (_m *Repository) GetAgentByName(ctx context.Context, name string) (entities.Agent, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetAgentByName")
	}

	var r0 entities.Agent
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.Agent); ok {
		r0 = rf(ctx, name)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(entities.Agent)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// GetDefaultAgent provides a mock function
func (_m *Repository) GetDefaultAgent(ctx context.Context) (entities.Agent, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultAgent")
	}

	var r0 entities.Agent
	if rf, ok := ret.Get(0).(func(context.Context) entities.Agent); ok {
		r0 = rf(ctx)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(entities.Agent)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// ListAgents provides a mock function
func (_m *Repository) ListAgents(ctx context.Context) ([]entities.Agent, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAgents")
	}

	var r0 []entities.Agent
	if rf, ok := ret.Get(0).(func(context.Context) []entities.Agent); ok {
		r0 = rf(ctx)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]entities.Agent)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// DeleteAgent provides a mock function
func (_m *Repository) DeleteAgent(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAgent")
	}

	r0 := ret.Error(0)
	return r0
}

// SetAgentPaused provides a mock function
func (_m *Repository) SetAgentPaused(ctx context.Context, id uint, paused bool) (entities.Agent, error) {
	ret := _m.Called(ctx, id, paused)

	if len(ret) == 0 {
		panic("no return value specified for SetAgentPaused")
	}

	var r0 entities.Agent
	if rf, ok := ret.Get(0).(func(context.Context, uint, bool) entities.Agent); ok {
		r0 = rf(ctx, id, paused)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(entities.Agent)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// EnsureDefaultAgent provides a mock function
func (_m *Repository) EnsureDefaultAgent(ctx context.Context) (entities.Agent, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for EnsureDefaultAgent")
	}

	var r0 entities.Agent
	if rf, ok := ret.Get(0).(func(context.Context) entities.Agent); ok {
		r0 = rf(ctx)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(entities.Agent)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// SetBindings provides a mock function
func (_m *Repository) SetBindings(ctx context.Context, agentID uint, strategyIDs []uint) error {
	ret := _m.Called(ctx, agentID, strategyIDs)

	if len(ret) == 0 {
		panic("no return value specified for SetBindings")
	}

	r0 := ret.Error(0)
	return r0
}

// ListBindingsByAgent provides a mock function
func (_m *Repository) ListBindingsByAgent(ctx context.Context, agentID uint) ([]entities.AgentStrategyBinding, error) {
	ret := _m.Called(ctx, agentID)

	if len(ret) == 0 {
		panic("no return value specified for ListBindingsByAgent")
	}

	var r0 []entities.AgentStrategyBinding
	if rf, ok := ret.Get(0).(func(context.Context, uint) []entities.AgentStrategyBinding); ok {
		r0 = rf(ctx, agentID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]entities.AgentStrategyBinding)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// ListAgentsByStrategy provides a mock function
func (_m *Repository) ListAgentsByStrategy(ctx context.Context, strategyID uint) ([]entities.Agent, error) {
	ret := _m.Called(ctx, strategyID)

	if len(ret) == 0 {
		panic("no return value specified for ListAgentsByStrategy")
	}

	var r0 []entities.Agent
	if rf, ok := ret.Get(0).(func(context.Context, uint) []entities.Agent); ok {
		r0 = rf(ctx, strategyID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]entities.Agent)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// AppendMemory provides a mock function
func (_m *Repository) AppendMemory(ctx context.Context, entry entities.StrategyMemoryEntry) (entities.StrategyMemoryEntry, error) {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for AppendMemory")
	}

	var r0 entities.StrategyMemoryEntry
	if rf, ok := ret.Get(0).(func(context.Context, entities.StrategyMemoryEntry) entities.StrategyMemoryEntry); ok {
		r0 = rf(ctx, entry)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(entities.StrategyMemoryEntry)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// ListMemory provides a mock function
func (_m *Repository) ListMemory(ctx context.Context, strategyID uint, kinds []entities.MemoryKind, limit int, beforeID *uint) ([]entities.StrategyMemoryEntry, error) {
	ret := _m.Called(ctx, strategyID, kinds, limit, beforeID)

	if len(ret) == 0 {
		panic("no return value specified for ListMemory")
	}

	var r0 []entities.StrategyMemoryEntry
	if rf, ok := ret.Get(0).(func(context.Context, uint, []entities.MemoryKind, int, *uint) []entities.StrategyMemoryEntry); ok {
		r0 = rf(ctx, strategyID, kinds, limit, beforeID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]entities.StrategyMemoryEntry)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// CreateReport provides a mock function
func (_m *Repository) CreateReport(ctx context.Context, r entities.AgentReport) (entities.AgentReport, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for CreateReport")
	}

	var r0 entities.AgentReport
	if rf, ok := ret.Get(0).(func(context.Context, entities.AgentReport) entities.AgentReport); ok {
		r0 = rf(ctx, r)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(entities.AgentReport)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// GetReport provides a mock function
func (_m *Repository) GetReport(ctx context.Context, id uint) (entities.AgentReport, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetReport")
	}

	var r0 entities.AgentReport
	if rf, ok := ret.Get(0).(func(context.Context, uint) entities.AgentReport); ok {
		r0 = rf(ctx, id)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(entities.AgentReport)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// ListReports provides a mock function
func (_m *Repository) ListReports(ctx context.Context, filter agentplatform.ReportFilter) ([]entities.AgentReport, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListReports")
	}

	var r0 []entities.AgentReport
	if rf, ok := ret.Get(0).(func(context.Context, agentplatform.ReportFilter) []entities.AgentReport); ok {
		r0 = rf(ctx, filter)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]entities.AgentReport)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// CreateWebhookTarget provides a mock function
func (_m *Repository) CreateWebhookTarget(ctx context.Context, t entities.WebhookTarget) (entities.WebhookTarget, error) {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for CreateWebhookTarget")
	}

	var r0 entities.WebhookTarget
	if rf, ok := ret.Get(0).(func(context.Context, entities.WebhookTarget) entities.WebhookTarget); ok {
		r0 = rf(ctx, t)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(entities.WebhookTarget)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// UpdateWebhookTarget provides a mock function
func (_m *Repository) UpdateWebhookTarget(ctx context.Context, t entities.WebhookTarget) (entities.WebhookTarget, error) {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWebhookTarget")
	}

	var r0 entities.WebhookTarget
	if rf, ok := ret.Get(0).(func(context.Context, entities.WebhookTarget) entities.WebhookTarget); ok {
		r0 = rf(ctx, t)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(entities.WebhookTarget)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// GetWebhookTarget provides a mock function
func (_m *Repository) GetWebhookTarget(ctx context.Context, id uint) (entities.WebhookTarget, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetWebhookTarget")
	}

	var r0 entities.WebhookTarget
	if rf, ok := ret.Get(0).(func(context.Context, uint) entities.WebhookTarget); ok {
		r0 = rf(ctx, id)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(entities.WebhookTarget)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// ListWebhookTargets provides a mock function
func (_m *Repository) ListWebhookTargets(ctx context.Context) ([]entities.WebhookTarget, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListWebhookTargets")
	}

	var r0 []entities.WebhookTarget
	if rf, ok := ret.Get(0).(func(context.Context) []entities.WebhookTarget); ok {
		r0 = rf(ctx)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]entities.WebhookTarget)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// DeleteWebhookTarget provides a mock function
func (_m *Repository) DeleteWebhookTarget(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWebhookTarget")
	}

	r0 := ret.Error(0)
	return r0
}

// ListWebhookTargetsByIDs provides a mock function
func (_m *Repository) ListWebhookTargetsByIDs(ctx context.Context, ids []uint) ([]entities.WebhookTarget, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for ListWebhookTargetsByIDs")
	}

	var r0 []entities.WebhookTarget
	if rf, ok := ret.Get(0).(func(context.Context, []uint) []entities.WebhookTarget); ok {
		r0 = rf(ctx, ids)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]entities.WebhookTarget)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// AddUsage provides a mock function
func (_m *Repository) AddUsage(ctx context.Context, agentID uint, day time.Time, inTok int64, outTok int64, cost float64) error {
	ret := _m.Called(ctx, agentID, day, inTok, outTok, cost)

	if len(ret) == 0 {
		panic("no return value specified for AddUsage")
	}

	r0 := ret.Error(0)
	return r0
}

// IncRuns provides a mock function
func (_m *Repository) IncRuns(ctx context.Context, agentID uint, day time.Time) error {
	ret := _m.Called(ctx, agentID, day)

	if len(ret) == 0 {
		panic("no return value specified for IncRuns")
	}

	r0 := ret.Error(0)
	return r0
}

// GetUsage provides a mock function
func (_m *Repository) GetUsage(ctx context.Context, agentID uint, day time.Time) (entities.AgentUsage, error) {
	ret := _m.Called(ctx, agentID, day)

	if len(ret) == 0 {
		panic("no return value specified for GetUsage")
	}

	var r0 entities.AgentUsage
	if rf, ok := ret.Get(0).(func(context.Context, uint, time.Time) entities.AgentUsage); ok {
		r0 = rf(ctx, agentID, day)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(entities.AgentUsage)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// ListUsage provides a mock function
func (_m *Repository) ListUsage(ctx context.Context, agentID uint, from time.Time, to time.Time) ([]entities.AgentUsage, error) {
	ret := _m.Called(ctx, agentID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListUsage")
	}

	var r0 []entities.AgentUsage
	if rf, ok := ret.Get(0).(func(context.Context, uint, time.Time, time.Time) []entities.AgentUsage); ok {
		r0 = rf(ctx, agentID, from, to)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]entities.AgentUsage)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// MarkBudgetAlertSent provides a mock function
func (_m *Repository) MarkBudgetAlertSent(ctx context.Context, agentID uint, day time.Time) (bool, error) {
	ret := _m.Called(ctx, agentID, day)

	if len(ret) == 0 {
		panic("no return value specified for MarkBudgetAlertSent")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, uint, time.Time) bool); ok {
		r0 = rf(ctx, agentID, day)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(bool)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// NewRepository creates a new instance of Repository and registers cleanup assertions.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	m := &Repository{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}

// AddBinding provides a mock function
func (_m *Repository) AddBinding(ctx context.Context, agentID uint, strategyID uint) error {
	ret := _m.Called(ctx, agentID, strategyID)

	if len(ret) == 0 {
		panic("no return value specified for AddBinding")
	}

	r0 := ret.Error(0)
	return r0
}

// TryIncAutoDeploys provides a mock function
func (_m *Repository) TryIncAutoDeploys(ctx context.Context, agentID uint, day time.Time, max int) (bool, error) {
	ret := _m.Called(ctx, agentID, day, max)

	if len(ret) == 0 {
		panic("no return value specified for TryIncAutoDeploys")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, uint, time.Time, int) bool); ok {
		r0 = rf(ctx, agentID, day, max)
	} else {
		r0 = ret.Get(0).(bool)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// TryIncStrategiesCreated provides a mock function
func (_m *Repository) TryIncStrategiesCreated(ctx context.Context, agentID uint, day time.Time, max int) (bool, error) {
	ret := _m.Called(ctx, agentID, day, max)

	if len(ret) == 0 {
		panic("no return value specified for TryIncStrategiesCreated")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, uint, time.Time, int) bool); ok {
		r0 = rf(ctx, agentID, day, max)
	} else {
		r0 = ret.Get(0).(bool)
	}
	r1 := ret.Error(1)
	return r0, r1
}
