// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "go-trade-bot/app/entities"

	mock "github.com/stretchr/testify/mock"
)

// StrategyRepository is an autogenerated mock type for the StrategyRepository type
type StrategyRepository struct {
	mock.Mock
}

func (_m *StrategyRepository) SaveExecution(ctx context.Context, execution entities.StrategyExecution) error {
	ret := _m.Called(ctx, execution)
	return ret.Error(0)
}

func (_m *StrategyRepository) GetByID(ctx context.Context, id uint) (entities.Strategy, error) {
	ret := _m.Called(ctx, id)

	var r0 entities.Strategy
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(entities.Strategy)
	}
	return r0, ret.Error(1)
}

func (_m *StrategyRepository) CountOpenSignals(ctx context.Context, strategy entities.Strategy) (int64, error) {
	ret := _m.Called(ctx, strategy)
	return ret.Get(0).(int64), ret.Error(1)
}

// NewStrategyRepository creates a new instance of StrategyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStrategyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StrategyRepository {
	mock := &StrategyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
