// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	entities "go-trade-bot/app/entities"

	mock "github.com/stretchr/testify/mock"
)

// StrategyWorker is an autogenerated mock type for the StrategyWorker type
type StrategyWorker struct {
	mock.Mock
}

func (_m *StrategyWorker) EnqueueStrategyTask(strategy entities.Strategy) error {
	ret := _m.Called(strategy)
	return ret.Error(0)
}

// NewStrategyWorker creates a new instance of StrategyWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStrategyWorker(t interface {
	mock.TestingT
	Cleanup(func())
}) *StrategyWorker {
	mock := &StrategyWorker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
