// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "go-trade-bot/app/entities"
	strategies "go-trade-bot/app/strategies"

	mock "github.com/stretchr/testify/mock"
)

// Engine is an autogenerated mock type for the Engine type
type Engine struct {
	mock.Mock
}

func (_m *Engine) Run(ctx context.Context, strategy strategies.Strategy, dbStrategy entities.Strategy, symbol string, mode strategies.ExecutionMode) error {
	ret := _m.Called(ctx, strategy, dbStrategy, symbol, mode)
	return ret.Error(0)
}

// NewEngine creates a new instance of Engine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *Engine {
	mock := &Engine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
