version: '3.8' # Versão do Docker Compose

services:
  app:
    build:
      context: .  # Diretório atual contendo o Dockerfile
      dockerfile: Dockerfile # Nome do Dockerfile
    container_name: go-trade-bot
    ports:
      - "8080:8080" # Mapeia a porta 8080 do host para a porta 8080 do contêiner
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Mapeia a porta 6379 do host para a porta 6379 do contêiner
    volumes:
      - redis_data:/data # Volumes para persistência de dados

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # Mapeia a porta 27017 do host para a porta 27017 do contêiner
    volumes:
      - mongo_data:/data/db # Volumes para persistência de dados

volumes:
  redis_data:
  mongo_data: