version: '3.8' 

services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile 
    container_name: go-trade-bot
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" 
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  redis_data:
  mongo_data: