// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	entities "go-trade-bot/app/entities"

	mock "github.com/stretchr/testify/mock"
)

// StrategyWorker is an autogenerated mock type for the StrategyWorker type
type StrategyWorker struct {
	mock.Mock
}

// EnqueueStrategyTask provides a mock function with given fields: strategy
func (_m *StrategyWorker) EnqueueStrategyTask(strategy entities.Strategy) error {
	ret := _m.Called(strategy)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueStrategyTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.Strategy) error); ok {
		r0 = rf(strategy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStrategyWorker creates a new instance of StrategyWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStrategyWorker(t interface {
	mock.TestingT
	Cleanup(func())
}) *StrategyWorker {
	mock := &StrategyWorker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
