// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "go-trade-bot/app/entities"

	mock "github.com/stretchr/testify/mock"
)

// StrategyRepository is an autogenerated mock type for the StrategyRepository type
type StrategyRepository struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *StrategyRepository) GetAll(ctx context.Context) ([]entities.Strategy, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []entities.Strategy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entities.Strategy, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entities.Strategy); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Strategy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *StrategyRepository) GetByID(ctx context.Context, id uint) (entities.Strategy, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 entities.Strategy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (entities.Strategy, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) entities.Strategy); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.Strategy)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetScriptVersions provides a mock function with given fields: ctx, strategyID
func (_m *StrategyRepository) GetScriptVersions(ctx context.Context, strategyID uint) ([]entities.ScriptVersion, error) {
	ret := _m.Called(ctx, strategyID)

	if len(ret) == 0 {
		panic("no return value specified for GetScriptVersions")
	}

	var r0 []entities.ScriptVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]entities.ScriptVersion, error)); ok {
		return rf(ctx, strategyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []entities.ScriptVersion); ok {
		r0 = rf(ctx, strategyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.ScriptVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, strategyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, strategy
func (_m *StrategyRepository) Save(ctx context.Context, strategy entities.Strategy) error {
	ret := _m.Called(ctx, strategy)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Strategy) error); ok {
		r0 = rf(ctx, strategy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, strategy
func (_m *StrategyRepository) Update(ctx context.Context, strategy entities.Strategy) error {
	ret := _m.Called(ctx, strategy)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Strategy) error); ok {
		r0 = rf(ctx, strategy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveScriptVersion provides a mock function with given fields: ctx, v
func (_m *StrategyRepository) SaveScriptVersion(ctx context.Context, v entities.ScriptVersion) error {
	ret := _m.Called(ctx, v)

	if len(ret) == 0 {
		panic("no return value specified for SaveScriptVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.ScriptVersion) error); ok {
		r0 = rf(ctx, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetStrategyPerformanceBySymbol provides a mock function with given fields: ctx
func (_m *StrategyRepository) GetStrategyPerformanceBySymbol(ctx context.Context) []entities.StrategyPerformance {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStrategyPerformanceBySymbol")
	}

	var r0 []entities.StrategyPerformance
	if rf, ok := ret.Get(0).(func(context.Context) []entities.StrategyPerformance); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.StrategyPerformance)
		}
	}

	return r0
}

// NewStrategyRepository creates a new instance of StrategyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStrategyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StrategyRepository {
	mock := &StrategyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
