// Code generated by hand to match mockery v2.53.2 conventions (mockery's
// embedded go1.24 parser cannot load this go1.25 module). DO NOT EDIT by hand
// without keeping every method in sync with the interface.

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	entities "go-trade-bot/app/entities"
)

// AgentRepository is a mock type for the AgentRepository type
type AgentRepository struct {
	mock.Mock
}

// GetAgent provides a mock function
func (_m *AgentRepository) GetAgent(ctx context.Context, id uint) (entities.Agent, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAgent")
	}

	var r0 entities.Agent
	if rf, ok := ret.Get(0).(func(context.Context, uint) entities.Agent); ok {
		r0 = rf(ctx, id)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(entities.Agent)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// ListBindingsByAgent provides a mock function
func (_m *AgentRepository) ListBindingsByAgent(ctx context.Context, agentID uint) ([]entities.AgentStrategyBinding, error) {
	ret := _m.Called(ctx, agentID)

	if len(ret) == 0 {
		panic("no return value specified for ListBindingsByAgent")
	}

	var r0 []entities.AgentStrategyBinding
	if rf, ok := ret.Get(0).(func(context.Context, uint) []entities.AgentStrategyBinding); ok {
		r0 = rf(ctx, agentID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]entities.AgentStrategyBinding)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// NewAgentRepository creates a new instance of AgentRepository and registers cleanup assertions.
func NewAgentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AgentRepository {
	m := &AgentRepository{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
