// Code generated by hand to match mockery v2.53.2 conventions (mockery's
// embedded go1.24 parser cannot load this go1.25 module). DO NOT EDIT by hand
// without keeping every method in sync with the interface.

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	entities "go-trade-bot/app/entities"
)

// CronSource is a mock type for the CronSource type
type CronSource struct {
	mock.Mock
}

// ListAgents provides a mock function
func (_m *CronSource) ListAgents(ctx context.Context) ([]entities.Agent, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAgents")
	}

	var r0 []entities.Agent
	if rf, ok := ret.Get(0).(func(context.Context) []entities.Agent); ok {
		r0 = rf(ctx)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]entities.Agent)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// ListBindingsByAgent provides a mock function
func (_m *CronSource) ListBindingsByAgent(ctx context.Context, agentID uint) ([]entities.AgentStrategyBinding, error) {
	ret := _m.Called(ctx, agentID)

	if len(ret) == 0 {
		panic("no return value specified for ListBindingsByAgent")
	}

	var r0 []entities.AgentStrategyBinding
	if rf, ok := ret.Get(0).(func(context.Context, uint) []entities.AgentStrategyBinding); ok {
		r0 = rf(ctx, agentID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]entities.AgentStrategyBinding)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// NewCronSource creates a new instance of CronSource and registers cleanup assertions.
func NewCronSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *CronSource {
	m := &CronSource{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
