// Code generated by hand to match mockery v2.53.2 conventions (mockery's
// embedded go1.24 parser cannot load this go1.25 module). DO NOT EDIT by hand
// without keeping every method in sync with the interface.

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	entities "go-trade-bot/app/entities"
)

// SettingsReader is a mock type for the SettingsReader type
type SettingsReader struct {
	mock.Mock
}

// Get provides a mock function
func (_m *SettingsReader) Get(ctx context.Context) (*entities.Settings, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entities.Settings
	if rf, ok := ret.Get(0).(func(context.Context) *entities.Settings); ok {
		r0 = rf(ctx)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*entities.Settings)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// NewSettingsReader creates a new instance of SettingsReader and registers cleanup assertions.
func NewSettingsReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *SettingsReader {
	m := &SettingsReader{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
