// Code generated by hand to match mockery v2.53.2 conventions (mockery's
// embedded go1.24 parser cannot load this go1.25 module). DO NOT EDIT by hand
// without keeping every method in sync with the interface.

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	entities "go-trade-bot/app/entities"
	agentusecase "go-trade-bot/app/usecase/agent"
)

// UseCase is a mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// Run provides a mock function
func (_m *UseCase) Run(ctx context.Context, req agentusecase.RunRequest) (entities.AgentRun, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 entities.AgentRun
	if rf, ok := ret.Get(0).(func(context.Context, agentusecase.RunRequest) entities.AgentRun); ok {
		r0 = rf(ctx, req)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(entities.AgentRun)
	}
	r1 := ret.Error(1)
	return r0, r1
}

// NewUseCase creates a new instance of UseCase and registers cleanup assertions.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	m := &UseCase{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
