// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// OptimizeUseCase is an autogenerated mock type for the OptimizeUseCase type
type OptimizeUseCase struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, runID
func (_m *OptimizeUseCase) Run(ctx context.Context, runID uint) error {
	ret := _m.Called(ctx, runID)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, runID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOptimizeUseCase creates a new instance of OptimizeUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOptimizeUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *OptimizeUseCase {
	mock := &OptimizeUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
