// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "go-trade-bot/app/entities"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// SnapshotRepository is an autogenerated mock type for the SnapshotRepository type
type SnapshotRepository struct {
	mock.Mock
}

// ListDaily provides a mock function with given fields: ctx, strategyID, symbol, from, to
func (_m *SnapshotRepository) ListDaily(ctx context.Context, strategyID uint, symbol string, from time.Time, to time.Time) ([]entities.StrategyPerformanceSnapshot, error) {
	ret := _m.Called(ctx, strategyID, symbol, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListDaily")
	}

	var r0 []entities.StrategyPerformanceSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, time.Time, time.Time) ([]entities.StrategyPerformanceSnapshot, error)); ok {
		return rf(ctx, strategyID, symbol, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, time.Time, time.Time) []entities.StrategyPerformanceSnapshot); ok {
		r0 = rf(ctx, strategyID, symbol, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.StrategyPerformanceSnapshot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, strategyID, symbol, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: ctx, snapshot
func (_m *SnapshotRepository) Upsert(ctx context.Context, snapshot entities.StrategyPerformanceSnapshot) error {
	ret := _m.Called(ctx, snapshot)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.StrategyPerformanceSnapshot) error); ok {
		r0 = rf(ctx, snapshot)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSnapshotRepository creates a new instance of SnapshotRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSnapshotRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SnapshotRepository {
	mock := &SnapshotRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
