// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "go-trade-bot/app/entities"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// StrategyRepository is an autogenerated mock type for the StrategyRepository type
type StrategyRepository struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *StrategyRepository) GetByID(ctx context.Context, id uint) (entities.Strategy, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 entities.Strategy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (entities.Strategy, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) entities.Strategy); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.Strategy)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPerformanceInRange provides a mock function with given fields: ctx, from, to
func (_m *StrategyRepository) GetPerformanceInRange(ctx context.Context, from time.Time, to time.Time) ([]entities.StrategyPerformance, error) {
	ret := _m.Called(ctx, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetPerformanceInRange")
	}

	var r0 []entities.StrategyPerformance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]entities.StrategyPerformance, error)); ok {
		return rf(ctx, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []entities.StrategyPerformance); ok {
		r0 = rf(ctx, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.StrategyPerformance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStrategyRepository creates a new instance of StrategyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStrategyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StrategyRepository {
	mock := &StrategyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
