// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	exchange "go-trade-bot/internal/exchange"
	indicators "go-trade-bot/internal/indicators"

	mock "github.com/stretchr/testify/mock"
)

// IndicatorProvider is an autogenerated mock type for the IndicatorProvider type
type IndicatorProvider struct {
	mock.Mock
}

// RSI provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) RSI(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for RSI")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// EMA provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) EMA(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for EMA")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// SMA provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) SMA(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for SMA")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// ATR provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) ATR(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for ATR")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// BollingerBands provides a mock function with given fields: candles, period, stdDevUp, stdDevDown, maType
func (_m *IndicatorProvider) BollingerBands(candles []exchange.Candle, period int, stdDevUp float64, stdDevDown float64, maType indicators.MAType) ([]float64, []float64, []float64) {
	ret := _m.Called(candles, period, stdDevUp, stdDevDown, maType)

	if len(ret) == 0 {
		panic("no return value specified for BollingerBands")
	}

	var r0, r1, r2 []float64
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}
	if ret.Get(1) != nil {
		r1 = ret.Get(1).([]float64)
	}
	if ret.Get(2) != nil {
		r2 = ret.Get(2).([]float64)
	}

	return r0, r1, r2
}

// MACD provides a mock function with given fields: candles, fastPeriod, slowPeriod, signalPeriod
func (_m *IndicatorProvider) MACD(candles []exchange.Candle, fastPeriod int, slowPeriod int, signalPeriod int) ([]float64, []float64, []float64) {
	ret := _m.Called(candles, fastPeriod, slowPeriod, signalPeriod)

	if len(ret) == 0 {
		panic("no return value specified for MACD")
	}

	var r0, r1, r2 []float64
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}
	if ret.Get(1) != nil {
		r1 = ret.Get(1).([]float64)
	}
	if ret.Get(2) != nil {
		r2 = ret.Get(2).([]float64)
	}

	return r0, r1, r2
}

// NewIndicatorProvider creates a new instance of IndicatorProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIndicatorProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *IndicatorProvider {
	mock := &IndicatorProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
