// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	exchange "go-trade-bot/internal/exchange"
	indicators "go-trade-bot/internal/indicators"

	mock "github.com/stretchr/testify/mock"
)

// IndicatorProvider is an autogenerated mock type for the IndicatorProvider type
type IndicatorProvider struct {
	mock.Mock
}

// RSI provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) RSI(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for RSI")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// EMA provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) EMA(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for EMA")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// SMA provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) SMA(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for SMA")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// ATR provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) ATR(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for ATR")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// BollingerBands provides a mock function with given fields: candles, period, stdDevUp, stdDevDown, maType
func (_m *IndicatorProvider) BollingerBands(candles []exchange.Candle, period int, stdDevUp float64, stdDevDown float64, maType indicators.MAType) ([]float64, []float64, []float64) {
	ret := _m.Called(candles, period, stdDevUp, stdDevDown, maType)

	if len(ret) == 0 {
		panic("no return value specified for BollingerBands")
	}

	var r0, r1, r2 []float64
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}
	if ret.Get(1) != nil {
		r1 = ret.Get(1).([]float64)
	}
	if ret.Get(2) != nil {
		r2 = ret.Get(2).([]float64)
	}

	return r0, r1, r2
}

// MACD provides a mock function with given fields: candles, fastPeriod, slowPeriod, signalPeriod
func (_m *IndicatorProvider) MACD(candles []exchange.Candle, fastPeriod int, slowPeriod int, signalPeriod int) ([]float64, []float64, []float64) {
	ret := _m.Called(candles, fastPeriod, slowPeriod, signalPeriod)

	if len(ret) == 0 {
		panic("no return value specified for MACD")
	}

	var r0, r1, r2 []float64
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}
	if ret.Get(1) != nil {
		r1 = ret.Get(1).([]float64)
	}
	if ret.Get(2) != nil {
		r2 = ret.Get(2).([]float64)
	}

	return r0, r1, r2
}

// DEMA provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) DEMA(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for DEMA")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// HTTrendline provides a mock function with given fields: candles
func (_m *IndicatorProvider) HTTrendline(candles []exchange.Candle) []float64 {
	ret := _m.Called(candles)

	if len(ret) == 0 {
		panic("no return value specified for HTTrendline")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle) []float64); ok {
		r0 = rf(candles)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// KAMA provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) KAMA(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for KAMA")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// MA provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) MA(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for MA")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// MAMA provides a mock function with given fields: candles, fastLimit, slowLimit
func (_m *IndicatorProvider) MAMA(candles []exchange.Candle, fastLimit float64, slowLimit float64) (mama []float64, fama []float64) {
	ret := _m.Called(candles, fastLimit, slowLimit)

	if len(ret) == 0 {
		panic("no return value specified for MAMA")
	}

	var r0 []float64
	var r1 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, float64, float64) ([]float64, []float64)); ok {
		r0, r1 = rf(candles, fastLimit, slowLimit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]float64)
		}
	}

	return r0, r1
}

// MidPoint provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) MidPoint(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for MidPoint")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// MidPrice provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) MidPrice(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for MidPrice")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// SAR provides a mock function with given fields: candles, acceleration, maximum
func (_m *IndicatorProvider) SAR(candles []exchange.Candle, acceleration float64, maximum float64) []float64 {
	ret := _m.Called(candles, acceleration, maximum)

	if len(ret) == 0 {
		panic("no return value specified for SAR")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, float64, float64) []float64); ok {
		r0 = rf(candles, acceleration, maximum)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// SARExt provides a mock function with given fields: candles, startValue, offsetOnReverse, accelerationInitLong, accelerationLong, accelerationMaxLong, accelerationInitShort, accelerationShort, accelerationMaxShort
func (_m *IndicatorProvider) SARExt(candles []exchange.Candle, startValue float64, offsetOnReverse float64, accelerationInitLong float64, accelerationLong float64, accelerationMaxLong float64, accelerationInitShort float64, accelerationShort float64, accelerationMaxShort float64) []float64 {
	ret := _m.Called(candles, startValue, offsetOnReverse, accelerationInitLong, accelerationLong, accelerationMaxLong, accelerationInitShort, accelerationShort, accelerationMaxShort)

	if len(ret) == 0 {
		panic("no return value specified for SARExt")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, float64, float64, float64, float64, float64, float64, float64, float64) []float64); ok {
		r0 = rf(candles, startValue, offsetOnReverse, accelerationInitLong, accelerationLong, accelerationMaxLong, accelerationInitShort, accelerationShort, accelerationMaxShort)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// T3 provides a mock function with given fields: candles, period, vFactor
func (_m *IndicatorProvider) T3(candles []exchange.Candle, period int, vFactor float64) []float64 {
	ret := _m.Called(candles, period, vFactor)

	if len(ret) == 0 {
		panic("no return value specified for T3")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int, float64) []float64); ok {
		r0 = rf(candles, period, vFactor)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// TEMA provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) TEMA(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for TEMA")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// TRIMA provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) TRIMA(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for TRIMA")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// WMA provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) WMA(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for WMA")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// ADX provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) ADX(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for ADX")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// ADXR provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) ADXR(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for ADXR")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// APO provides a mock function with given fields: candles, fastPeriod, slowPeriod
func (_m *IndicatorProvider) APO(candles []exchange.Candle, fastPeriod int, slowPeriod int) []float64 {
	ret := _m.Called(candles, fastPeriod, slowPeriod)

	if len(ret) == 0 {
		panic("no return value specified for APO")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int, int) []float64); ok {
		r0 = rf(candles, fastPeriod, slowPeriod)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// Aroon provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) Aroon(candles []exchange.Candle, period int) (down []float64, up []float64) {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for Aroon")
	}

	var r0 []float64
	var r1 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) ([]float64, []float64)); ok {
		r0, r1 = rf(candles, period)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]float64)
		}
	}

	return r0, r1
}

// AroonOsc provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) AroonOsc(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for AroonOsc")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// BOP provides a mock function with given fields: candles
func (_m *IndicatorProvider) BOP(candles []exchange.Candle) []float64 {
	ret := _m.Called(candles)

	if len(ret) == 0 {
		panic("no return value specified for BOP")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle) []float64); ok {
		r0 = rf(candles)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// CMO provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) CMO(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for CMO")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// CCI provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) CCI(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for CCI")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// DX provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) DX(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for DX")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// MACDExt provides a mock function with given fields: candles, fastPeriod, slowPeriod, signalPeriod
func (_m *IndicatorProvider) MACDExt(candles []exchange.Candle, fastPeriod int, slowPeriod int, signalPeriod int) (macd []float64, signal []float64, hist []float64) {
	ret := _m.Called(candles, fastPeriod, slowPeriod, signalPeriod)

	if len(ret) == 0 {
		panic("no return value specified for MACDExt")
	}

	var r0 []float64
	var r1 []float64
	var r2 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int, int, int) ([]float64, []float64, []float64)); ok {
		r0, r1, r2 = rf(candles, fastPeriod, slowPeriod, signalPeriod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]float64)
		}
		if ret.Get(2) != nil {
			r2 = ret.Get(2).([]float64)
		}
	}

	return r0, r1, r2
}

// MACDFix provides a mock function with given fields: candles, signalPeriod
func (_m *IndicatorProvider) MACDFix(candles []exchange.Candle, signalPeriod int) (macd []float64, signal []float64, hist []float64) {
	ret := _m.Called(candles, signalPeriod)

	if len(ret) == 0 {
		panic("no return value specified for MACDFix")
	}

	var r0 []float64
	var r1 []float64
	var r2 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) ([]float64, []float64, []float64)); ok {
		r0, r1, r2 = rf(candles, signalPeriod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]float64)
		}
		if ret.Get(2) != nil {
			r2 = ret.Get(2).([]float64)
		}
	}

	return r0, r1, r2
}

// MinusDI provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) MinusDI(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for MinusDI")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// MinusDM provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) MinusDM(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for MinusDM")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// MFI provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) MFI(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for MFI")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// Mom provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) Mom(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for Mom")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// PlusDI provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) PlusDI(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for PlusDI")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// PlusDM provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) PlusDM(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for PlusDM")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// PPO provides a mock function with given fields: candles, fastPeriod, slowPeriod
func (_m *IndicatorProvider) PPO(candles []exchange.Candle, fastPeriod int, slowPeriod int) []float64 {
	ret := _m.Called(candles, fastPeriod, slowPeriod)

	if len(ret) == 0 {
		panic("no return value specified for PPO")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int, int) []float64); ok {
		r0 = rf(candles, fastPeriod, slowPeriod)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// ROCP provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) ROCP(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for ROCP")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// ROC provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) ROC(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for ROC")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// ROCR provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) ROCR(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for ROCR")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// ROCR100 provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) ROCR100(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for ROCR100")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// Stoch provides a mock function with given fields: candles, fastKPeriod, slowKPeriod, slowDPeriod
func (_m *IndicatorProvider) Stoch(candles []exchange.Candle, fastKPeriod int, slowKPeriod int, slowDPeriod int) (k []float64, d []float64) {
	ret := _m.Called(candles, fastKPeriod, slowKPeriod, slowDPeriod)

	if len(ret) == 0 {
		panic("no return value specified for Stoch")
	}

	var r0 []float64
	var r1 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int, int, int) ([]float64, []float64)); ok {
		r0, r1 = rf(candles, fastKPeriod, slowKPeriod, slowDPeriod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]float64)
		}
	}

	return r0, r1
}

// StochF provides a mock function with given fields: candles, fastKPeriod, fastDPeriod
func (_m *IndicatorProvider) StochF(candles []exchange.Candle, fastKPeriod int, fastDPeriod int) (k []float64, d []float64) {
	ret := _m.Called(candles, fastKPeriod, fastDPeriod)

	if len(ret) == 0 {
		panic("no return value specified for StochF")
	}

	var r0 []float64
	var r1 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int, int) ([]float64, []float64)); ok {
		r0, r1 = rf(candles, fastKPeriod, fastDPeriod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]float64)
		}
	}

	return r0, r1
}

// StochRSI provides a mock function with given fields: candles, period, fastKPeriod, fastDPeriod
func (_m *IndicatorProvider) StochRSI(candles []exchange.Candle, period int, fastKPeriod int, fastDPeriod int) (k []float64, d []float64) {
	ret := _m.Called(candles, period, fastKPeriod, fastDPeriod)

	if len(ret) == 0 {
		panic("no return value specified for StochRSI")
	}

	var r0 []float64
	var r1 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int, int, int) ([]float64, []float64)); ok {
		r0, r1 = rf(candles, period, fastKPeriod, fastDPeriod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]float64)
		}
	}

	return r0, r1
}

// Trix provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) Trix(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for Trix")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// UltOsc provides a mock function with given fields: candles, period1, period2, period3
func (_m *IndicatorProvider) UltOsc(candles []exchange.Candle, period1 int, period2 int, period3 int) []float64 {
	ret := _m.Called(candles, period1, period2, period3)

	if len(ret) == 0 {
		panic("no return value specified for UltOsc")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int, int, int) []float64); ok {
		r0 = rf(candles, period1, period2, period3)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// WillR provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) WillR(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for WillR")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// AD provides a mock function with given fields: candles
func (_m *IndicatorProvider) AD(candles []exchange.Candle) []float64 {
	ret := _m.Called(candles)

	if len(ret) == 0 {
		panic("no return value specified for AD")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle) []float64); ok {
		r0 = rf(candles)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// ADOsc provides a mock function with given fields: candles, fastPeriod, slowPeriod
func (_m *IndicatorProvider) ADOsc(candles []exchange.Candle, fastPeriod int, slowPeriod int) []float64 {
	ret := _m.Called(candles, fastPeriod, slowPeriod)

	if len(ret) == 0 {
		panic("no return value specified for ADOsc")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int, int) []float64); ok {
		r0 = rf(candles, fastPeriod, slowPeriod)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// OBV provides a mock function with given fields: candles
func (_m *IndicatorProvider) OBV(candles []exchange.Candle) []float64 {
	ret := _m.Called(candles)

	if len(ret) == 0 {
		panic("no return value specified for OBV")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle) []float64); ok {
		r0 = rf(candles)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// NATR provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) NATR(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for NATR")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// TRange provides a mock function with given fields: candles
func (_m *IndicatorProvider) TRange(candles []exchange.Candle) []float64 {
	ret := _m.Called(candles)

	if len(ret) == 0 {
		panic("no return value specified for TRange")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle) []float64); ok {
		r0 = rf(candles)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// AvgPrice provides a mock function with given fields: candles
func (_m *IndicatorProvider) AvgPrice(candles []exchange.Candle) []float64 {
	ret := _m.Called(candles)

	if len(ret) == 0 {
		panic("no return value specified for AvgPrice")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle) []float64); ok {
		r0 = rf(candles)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// MedPrice provides a mock function with given fields: candles
func (_m *IndicatorProvider) MedPrice(candles []exchange.Candle) []float64 {
	ret := _m.Called(candles)

	if len(ret) == 0 {
		panic("no return value specified for MedPrice")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle) []float64); ok {
		r0 = rf(candles)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// TypPrice provides a mock function with given fields: candles
func (_m *IndicatorProvider) TypPrice(candles []exchange.Candle) []float64 {
	ret := _m.Called(candles)

	if len(ret) == 0 {
		panic("no return value specified for TypPrice")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle) []float64); ok {
		r0 = rf(candles)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// WclPrice provides a mock function with given fields: candles
func (_m *IndicatorProvider) WclPrice(candles []exchange.Candle) []float64 {
	ret := _m.Called(candles)

	if len(ret) == 0 {
		panic("no return value specified for WclPrice")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle) []float64); ok {
		r0 = rf(candles)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// HTDcPeriod provides a mock function with given fields: candles
func (_m *IndicatorProvider) HTDcPeriod(candles []exchange.Candle) []float64 {
	ret := _m.Called(candles)

	if len(ret) == 0 {
		panic("no return value specified for HTDcPeriod")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle) []float64); ok {
		r0 = rf(candles)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// HTDcPhase provides a mock function with given fields: candles
func (_m *IndicatorProvider) HTDcPhase(candles []exchange.Candle) []float64 {
	ret := _m.Called(candles)

	if len(ret) == 0 {
		panic("no return value specified for HTDcPhase")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle) []float64); ok {
		r0 = rf(candles)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// HTPhasor provides a mock function with given fields: candles
func (_m *IndicatorProvider) HTPhasor(candles []exchange.Candle) (inphase []float64, quadrature []float64) {
	ret := _m.Called(candles)

	if len(ret) == 0 {
		panic("no return value specified for HTPhasor")
	}

	var r0 []float64
	var r1 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle) ([]float64, []float64)); ok {
		r0, r1 = rf(candles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]float64)
		}
	}

	return r0, r1
}

// HTSine provides a mock function with given fields: candles
func (_m *IndicatorProvider) HTSine(candles []exchange.Candle) (sine []float64, leadSine []float64) {
	ret := _m.Called(candles)

	if len(ret) == 0 {
		panic("no return value specified for HTSine")
	}

	var r0 []float64
	var r1 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle) ([]float64, []float64)); ok {
		r0, r1 = rf(candles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]float64)
		}
	}

	return r0, r1
}

// HTTrendMode provides a mock function with given fields: candles
func (_m *IndicatorProvider) HTTrendMode(candles []exchange.Candle) []float64 {
	ret := _m.Called(candles)

	if len(ret) == 0 {
		panic("no return value specified for HTTrendMode")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle) []float64); ok {
		r0 = rf(candles)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// LinearReg provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) LinearReg(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for LinearReg")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// LinearRegAngle provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) LinearRegAngle(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for LinearRegAngle")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// LinearRegIntercept provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) LinearRegIntercept(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for LinearRegIntercept")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// LinearRegSlope provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) LinearRegSlope(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for LinearRegSlope")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// StdDev provides a mock function with given fields: candles, period, nbDev
func (_m *IndicatorProvider) StdDev(candles []exchange.Candle, period int, nbDev float64) []float64 {
	ret := _m.Called(candles, period, nbDev)

	if len(ret) == 0 {
		panic("no return value specified for StdDev")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int, float64) []float64); ok {
		r0 = rf(candles, period, nbDev)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// TSF provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) TSF(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for TSF")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// Var provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) Var(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for Var")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// Max provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) Max(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for Max")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// MaxIndex provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) MaxIndex(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for MaxIndex")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// Min provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) Min(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for Min")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// MinIndex provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) MinIndex(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for MinIndex")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// MinMax provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) MinMax(candles []exchange.Candle, period int) (min []float64, max []float64) {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for MinMax")
	}

	var r0 []float64
	var r1 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) ([]float64, []float64)); ok {
		r0, r1 = rf(candles, period)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]float64)
		}
	}

	return r0, r1
}

// MinMaxIndex provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) MinMaxIndex(candles []exchange.Candle, period int) (minIdx []float64, maxIdx []float64) {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for MinMaxIndex")
	}

	var r0 []float64
	var r1 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) ([]float64, []float64)); ok {
		r0, r1 = rf(candles, period)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]float64)
		}
	}

	return r0, r1
}

// Sum provides a mock function with given fields: candles, period
func (_m *IndicatorProvider) Sum(candles []exchange.Candle, period int) []float64 {
	ret := _m.Called(candles, period)

	if len(ret) == 0 {
		panic("no return value specified for Sum")
	}

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]exchange.Candle, int) []float64); ok {
		r0 = rf(candles, period)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]float64)
	}

	return r0
}

// NewIndicatorProvider creates a new instance of IndicatorProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIndicatorProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *IndicatorProvider {
	mock := &IndicatorProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
