// Code generated by hand to match mockery's conventions - DO NOT regenerate
// via `mockery` until its bundled Go parser supports the go1.25 language
// version emitted by protoc-gen-go into internal/grpc/strategypb (mockery
// v2.53.2's embedded toolchain is go1.24 as of this writing, and fails to
// parse strategy.pb.go with "package requires newer Go version go1.25").

package mocks

import (
	context "context"

	strategypb "go-trade-bot/internal/grpc/strategypb"

	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
)

// MLStrategyClient is a mock type for the strategypb.MLStrategyClient interface.
type MLStrategyClient struct {
	mock.Mock
}

func (_m *MLStrategyClient) Name(ctx context.Context, in *strategypb.Empty, opts ...grpc.CallOption) (*strategypb.NameResponse, error) {
	ret := _m.Called(ctx, in)
	var r0 *strategypb.NameResponse
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*strategypb.NameResponse)
	}
	return r0, ret.Error(1)
}

func (_m *MLStrategyClient) Before(ctx context.Context, in *strategypb.StrategyContext, opts ...grpc.CallOption) (*strategypb.Empty, error) {
	ret := _m.Called(ctx, in)
	var r0 *strategypb.Empty
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*strategypb.Empty)
	}
	return r0, ret.Error(1)
}

func (_m *MLStrategyClient) ShouldLong(ctx context.Context, in *strategypb.StrategyContext, opts ...grpc.CallOption) (*strategypb.BoolResponse, error) {
	ret := _m.Called(ctx, in)
	var r0 *strategypb.BoolResponse
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*strategypb.BoolResponse)
	}
	return r0, ret.Error(1)
}

func (_m *MLStrategyClient) GoLong(ctx context.Context, in *strategypb.StrategyContext, opts ...grpc.CallOption) (*strategypb.SignalResponse, error) {
	ret := _m.Called(ctx, in)
	var r0 *strategypb.SignalResponse
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*strategypb.SignalResponse)
	}
	return r0, ret.Error(1)
}

func (_m *MLStrategyClient) ShouldShort(ctx context.Context, in *strategypb.StrategyContext, opts ...grpc.CallOption) (*strategypb.BoolResponse, error) {
	ret := _m.Called(ctx, in)
	var r0 *strategypb.BoolResponse
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*strategypb.BoolResponse)
	}
	return r0, ret.Error(1)
}

func (_m *MLStrategyClient) GoShort(ctx context.Context, in *strategypb.StrategyContext, opts ...grpc.CallOption) (*strategypb.SignalResponse, error) {
	ret := _m.Called(ctx, in)
	var r0 *strategypb.SignalResponse
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*strategypb.SignalResponse)
	}
	return r0, ret.Error(1)
}

func (_m *MLStrategyClient) UpdatePosition(ctx context.Context, in *strategypb.StrategyContext, opts ...grpc.CallOption) (*strategypb.NullableSignalResponse, error) {
	ret := _m.Called(ctx, in)
	var r0 *strategypb.NullableSignalResponse
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*strategypb.NullableSignalResponse)
	}
	return r0, ret.Error(1)
}

func (_m *MLStrategyClient) After(ctx context.Context, in *strategypb.StrategyContext, opts ...grpc.CallOption) (*strategypb.Empty, error) {
	ret := _m.Called(ctx, in)
	var r0 *strategypb.Empty
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*strategypb.Empty)
	}
	return r0, ret.Error(1)
}

func (_m *MLStrategyClient) Terminate(ctx context.Context, in *strategypb.StrategyContext, opts ...grpc.CallOption) (*strategypb.Empty, error) {
	ret := _m.Called(ctx, in)
	var r0 *strategypb.Empty
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*strategypb.Empty)
	}
	return r0, ret.Error(1)
}

// NewMLStrategyClient creates a new instance of MLStrategyClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMLStrategyClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MLStrategyClient {
	m := &MLStrategyClient{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
