// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	exchange "go-trade-bot/internal/exchange"

	mock "github.com/stretchr/testify/mock"
)

// ExchangeClient is an autogenerated mock type for the ExchangeClient type
type ExchangeClient struct {
	mock.Mock
}

// PlaceOrder provides a mock function with given fields: ctx, order
func (_m *ExchangeClient) PlaceOrder(ctx context.Context, order exchange.PlaceOrderRequest) (exchange.OrderResult, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for PlaceOrder")
	}

	var r0 exchange.OrderResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, exchange.PlaceOrderRequest) (exchange.OrderResult, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, exchange.PlaceOrderRequest) exchange.OrderResult); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Get(0).(exchange.OrderResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, exchange.PlaceOrderRequest) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CancelOrder provides a mock function with given fields: ctx, symbol, orderID
func (_m *ExchangeClient) CancelOrder(ctx context.Context, symbol string, orderID string) error {
	ret := _m.Called(ctx, symbol, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, symbol, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOrder provides a mock function with given fields: ctx, symbol, orderID
func (_m *ExchangeClient) GetOrder(ctx context.Context, symbol string, orderID string) (exchange.OrderResult, error) {
	ret := _m.Called(ctx, symbol, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 exchange.OrderResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (exchange.OrderResult, error)); ok {
		return rf(ctx, symbol, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) exchange.OrderResult); ok {
		r0 = rf(ctx, symbol, orderID)
	} else {
		r0 = ret.Get(0).(exchange.OrderResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, symbol, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListKline provides a mock function with given fields: ctx, symbol, interval, limit
func (_m *ExchangeClient) ListKline(ctx context.Context, symbol string, interval string, limit int) ([]exchange.Candle, error) {
	ret := _m.Called(ctx, symbol, interval, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListKline")
	}

	var r0 []exchange.Candle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) ([]exchange.Candle, error)); ok {
		return rf(ctx, symbol, interval, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) []exchange.Candle); ok {
		r0 = rf(ctx, symbol, interval, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]exchange.Candle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(ctx, symbol, interval, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTickerPrices provides a mock function with given fields: ctx, symbol
func (_m *ExchangeClient) ListTickerPrices(ctx context.Context, symbol string) ([]exchange.TickerPrice, error) {
	ret := _m.Called(ctx, symbol)

	if len(ret) == 0 {
		panic("no return value specified for ListTickerPrices")
	}

	var r0 []exchange.TickerPrice
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]exchange.TickerPrice, error)); ok {
		return rf(ctx, symbol)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []exchange.TickerPrice); ok {
		r0 = rf(ctx, symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]exchange.TickerPrice)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountBalance provides a mock function with given fields: ctx
func (_m *ExchangeClient) GetAccountBalance(ctx context.Context) (exchange.AccountBalance, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountBalance")
	}

	var r0 exchange.AccountBalance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (exchange.AccountBalance, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) exchange.AccountBalance); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(exchange.AccountBalance)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscribeKline provides a mock function with given fields: ctx, symbol, interval
func (_m *ExchangeClient) SubscribeKline(ctx context.Context, symbol string, interval string) (<-chan exchange.Candle, error) {
	ret := _m.Called(ctx, symbol, interval)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeKline")
	}

	var r0 <-chan exchange.Candle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (<-chan exchange.Candle, error)); ok {
		return rf(ctx, symbol, interval)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) <-chan exchange.Candle); ok {
		r0 = rf(ctx, symbol, interval)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan exchange.Candle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, symbol, interval)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewExchangeClient creates a new instance of ExchangeClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExchangeClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExchangeClient {
	mock := &ExchangeClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
