// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	notifier "go-trade-bot/internal/notifier"

	mock "github.com/stretchr/testify/mock"
)

// NotificationSender is an autogenerated mock type for the NotificationSender type
type NotificationSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, event
func (_m *NotificationSender) Send(ctx context.Context, event notifier.Event) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, notifier.Event) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationSender creates a new instance of NotificationSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationSender {
	mock := &NotificationSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
