// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	entities "go-trade-bot/app/entities"
	usecase "go-trade-bot/app/usecase/signal"

	mock "github.com/stretchr/testify/mock"
)

// SignalUseCase is an autogenerated mock type for the SignalUseCase type
type SignalUseCase struct {
	mock.Mock
}

// GenerateBuySignal provides a mock function with given fields: e
func (_m *SignalUseCase) GenerateBuySignal(e usecase.EntrySignal) error {
	ret := _m.Called(e)

	if len(ret) == 0 {
		panic("no return value specified for GenerateBuySignal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(usecase.EntrySignal) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateSellSignal provides a mock function with given fields: e
func (_m *SignalUseCase) GenerateSellSignal(e usecase.ExitSignal) error {
	ret := _m.Called(e)

	if len(ret) == 0 {
		panic("no return value specified for GenerateSellSignal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(usecase.ExitSignal) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOpenSignal provides a mock function with given fields: symbol, strategyId
func (_m *SignalUseCase) GetOpenSignal(symbol string, strategyId uint) (entities.Signal, error) {
	ret := _m.Called(symbol, strategyId)

	if len(ret) == 0 {
		panic("no return value specified for GetOpenSignal")
	}

	var r0 entities.Signal
	var r1 error
	if rf, ok := ret.Get(0).(func(string, uint) (entities.Signal, error)); ok {
		return rf(symbol, strategyId)
	}
	if rf, ok := ret.Get(0).(func(string, uint) entities.Signal); ok {
		r0 = rf(symbol, strategyId)
	} else {
		r0 = ret.Get(0).(entities.Signal)
	}

	if rf, ok := ret.Get(1).(func(string, uint) error); ok {
		r1 = rf(symbol, strategyId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSignalUseCase creates a new instance of SignalUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSignalUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *SignalUseCase {
	mock := &SignalUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
