// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	strategies "go-trade-bot/app/strategies"

	mock "github.com/stretchr/testify/mock"
)

// Strategy is an autogenerated mock type for the strategies.Strategy type
type Strategy struct {
	mock.Mock
}

func (_m *Strategy) Name() string {
	ret := _m.Called()
	return ret.String(0)
}

func (_m *Strategy) Before(ctx strategies.Context) {
	_m.Called(ctx)
}

func (_m *Strategy) ShouldLong(ctx strategies.Context) bool {
	ret := _m.Called(ctx)
	return ret.Bool(0)
}

func (_m *Strategy) GoLong(ctx strategies.Context) strategies.Signal {
	ret := _m.Called(ctx)
	if ret.Get(0) == nil {
		return strategies.Signal{}
	}
	return ret.Get(0).(strategies.Signal)
}

func (_m *Strategy) ShouldShort(ctx strategies.Context) bool {
	ret := _m.Called(ctx)
	return ret.Bool(0)
}

func (_m *Strategy) GoShort(ctx strategies.Context) strategies.Signal {
	ret := _m.Called(ctx)
	if ret.Get(0) == nil {
		return strategies.Signal{}
	}
	return ret.Get(0).(strategies.Signal)
}

func (_m *Strategy) UpdatePosition(ctx strategies.Context) *strategies.Signal {
	ret := _m.Called(ctx)
	if ret.Get(0) == nil {
		return nil
	}
	return ret.Get(0).(*strategies.Signal)
}

func (_m *Strategy) After(ctx strategies.Context) {
	_m.Called(ctx)
}

func (_m *Strategy) Terminate(ctx strategies.Context) {
	_m.Called(ctx)
}

// NewStrategy creates a new instance of Strategy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStrategy(t interface {
	mock.TestingT
	Cleanup(func())
}) *Strategy {
	mock := &Strategy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
