// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	entities "go-trade-bot/app/entities"

	mock "github.com/stretchr/testify/mock"
)

// AccountReader is an autogenerated mock type for the AccountReader type
type AccountReader struct {
	mock.Mock
}

// GetAccount provides a mock function with no fields
func (_m *AccountReader) GetAccount() (entities.Account, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 entities.Account
	var r1 error
	if rf, ok := ret.Get(0).(func() (entities.Account, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() entities.Account); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(entities.Account)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAccountReader creates a new instance of AccountReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountReader {
	mock := &AccountReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
