// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"
	engine "go-trade-bot/app/engine"
	entities "go-trade-bot/app/entities"

	metrics_provider "go-trade-bot/internal/metrics_provider"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// BacktestRunner is an autogenerated mock type for the BacktestRunner type
type BacktestRunner struct {
	mock.Mock
}

// RunEphemeral provides a mock function with given fields: ctx, baseStrategy, symbol, timeframe, from, to, initialCapital, fillPolicy
func (_m *BacktestRunner) RunEphemeral(ctx context.Context, baseStrategy entities.Strategy, symbol string, timeframe string, from time.Time, to time.Time, initialCapital float64, fillPolicy engine.FillPolicy) (metrics_provider.BacktestMetrics, error) {
	ret := _m.Called(ctx, baseStrategy, symbol, timeframe, from, to, initialCapital, fillPolicy)

	if len(ret) == 0 {
		panic("no return value specified for RunEphemeral")
	}

	var r0 metrics_provider.BacktestMetrics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Strategy, string, string, time.Time, time.Time, float64, engine.FillPolicy) (metrics_provider.BacktestMetrics, error)); ok {
		return rf(ctx, baseStrategy, symbol, timeframe, from, to, initialCapital, fillPolicy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.Strategy, string, string, time.Time, time.Time, float64, engine.FillPolicy) metrics_provider.BacktestMetrics); ok {
		r0 = rf(ctx, baseStrategy, symbol, timeframe, from, to, initialCapital, fillPolicy)
	} else {
		r0 = ret.Get(0).(metrics_provider.BacktestMetrics)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.Strategy, string, string, time.Time, time.Time, float64, engine.FillPolicy) error); ok {
		r1 = rf(ctx, baseStrategy, symbol, timeframe, from, to, initialCapital, fillPolicy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBacktestRunner creates a new instance of BacktestRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBacktestRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *BacktestRunner {
	mock := &BacktestRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
