{
 "title": "TradeBot Status Page",
 "description": "Given status to all metrics on tradebot",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Profit",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(CASE WHEN o.order_operation = 'sell' THEN o.price * o.quantity ELSE 0 END) -\n  SUM(CASE WHEN o.order_operation = 'buy' THEN o.price * o.quantity ELSE 0 END) AS profit\nFROM\n  signals s\nJOIN\n  orders o ON s.id = o.signal_id\nJOIN\n  strategies st ON st.id = s.strategy_id\nwhere s.status = 'closed'"
    }
   ]
  },
  {
   "title": "Total Sell",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(CASE WHEN o.order_operation = 'sell' THEN o.price * o.quantity ELSE 0 END)  total_sell\nFROM\n  signals s\nJOIN\n  orders o ON s.id = o.signal_id\nJOIN\n  strategies st ON st.id = s.strategy_id\n"
    }
   ]
  },
  {
   "title": "Total Buy",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(CASE WHEN o.order_operation = 'buy' THEN o.price * o.quantity ELSE 0 END) AS total_buy\nFROM\n  signals s\nJOIN\n  orders o ON s.id = o.signal_id\nJOIN\n  strategies st ON st.id = s.strategy_id\nwhere s.status = 'open'\n\n  \n "
    }
   ]
  },
  {
   "title": "Signals Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  s.id,\n  s.symbol,\n  st.name,\n  SUM(CASE WHEN o.order_operation = 'sell' THEN o.price * o.quantity ELSE 0 END) AS total_sell,\n  SUM(CASE WHEN o.order_operation = 'buy' THEN o.price * o.quantity ELSE 0 END) AS total_buy,\n  SUM(CASE WHEN o.order_operation = 'sell' THEN o.price * o.quantity ELSE 0 END) -\n  SUM(CASE WHEN o.order_operation = 'buy' THEN o.price * o.quantity ELSE 0 END) AS profit\nFROM\n  signals s\nJOIN\n  orders o ON s.id = o.signal_id\nJOIN\n  strategies st ON st.id = s.strategy_id\nwhere s.status = 'closed'\nGROUP BY\n  s.id, s.symbol, s.status, st.name\norder by s.id desc"
    }
   ]
  },
  {
   "title": "Open signals",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  s.id,\n  s.symbol,\n  s.status,\n  st.name,\n  SUM(CASE WHEN o.order_operation = 'sell' THEN o.price * o.quantity ELSE 0 END) AS total_sell,\n  SUM(CASE WHEN o.order_operation = 'buy' THEN o.price * o.quantity ELSE 0 END) AS total_buy\nFROM\n  signals s\nJOIN\n  orders o ON s.id = o.signal_id\nJOIN\n  strategies st ON st.id = s.strategy_id\nwhere s.status = 'open'\nGROUP BY\n  s.id, s.symbol, s.status, st.name\norder by s.id desc"
    }
   ]
  },
  {
   "title": "Total Executions",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(se.id), s.name strategy\nFROM strategy_executions se \njoin strategies s on s.id = se.strategy_id\nWHERE   $__timeFilter(se.executed_at)\nGROUP BY s.name\nLIMIT 50 "
    }
   ]
  },
  {
   "title": "Executions By Strategy",
   "type": "table",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 22 },
   "targets": [
    {
     "rawSql": "select  \n  s.name, s.description, s.algorithm, s.monitored_symbols, s.cycle, count(se.id) total_executions\nFROM strategies s\njoin strategy_executions se on s.id = se.strategy_id\ngroup by s.name, s.description, s.algorithm, s.monitored_symbols, s.cycle"
    }
   ]
  },
  {
   "title": "Endpoint status by path",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "__auto" }
   ]
  }
 ]
}