// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "go-trade-bot/app/entities"

	mock "github.com/stretchr/testify/mock"

	optimize "go-trade-bot/app/usecase/optimize"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *UseCase) Create(ctx context.Context, req optimize.CreateRequest) (entities.OptimizationRun, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entities.OptimizationRun
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, optimize.CreateRequest) (entities.OptimizationRun, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, optimize.CreateRequest) entities.OptimizationRun); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(entities.OptimizationRun)
	}

	if rf, ok := ret.Get(1).(func(context.Context, optimize.CreateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *UseCase) GetByID(ctx context.Context, id uint) (entities.OptimizationRun, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 entities.OptimizationRun
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (entities.OptimizationRun, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) entities.OptimizationRun); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.OptimizationRun)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByStrategy provides a mock function with given fields: ctx, strategyID
func (_m *UseCase) ListByStrategy(ctx context.Context, strategyID uint) ([]entities.OptimizationRun, error) {
	ret := _m.Called(ctx, strategyID)

	if len(ret) == 0 {
		panic("no return value specified for ListByStrategy")
	}

	var r0 []entities.OptimizationRun
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]entities.OptimizationRun, error)); ok {
		return rf(ctx, strategyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []entities.OptimizationRun); ok {
		r0 = rf(ctx, strategyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.OptimizationRun)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, strategyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
