// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "go-trade-bot/app/entities"

	mock "github.com/stretchr/testify/mock"

	performancehistory "go-trade-bot/app/usecase/performancehistory"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// GetHistory provides a mock function with given fields: ctx, strategyID, symbol, bucket, limit
func (_m *UseCase) GetHistory(ctx context.Context, strategyID uint, symbol string, bucket entities.PerformanceBucket, limit int) ([]performancehistory.HistoryPoint, error) {
	ret := _m.Called(ctx, strategyID, symbol, bucket, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 []performancehistory.HistoryPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, entities.PerformanceBucket, int) ([]performancehistory.HistoryPoint, error)); ok {
		return rf(ctx, strategyID, symbol, bucket, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, entities.PerformanceBucket, int) []performancehistory.HistoryPoint); ok {
		r0 = rf(ctx, strategyID, symbol, bucket, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]performancehistory.HistoryPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string, entities.PerformanceBucket, int) error); ok {
		r1 = rf(ctx, strategyID, symbol, bucket, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
