// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: strategy.proto

package strategypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Context mirrors app/strategies.Context's fields exactly (frozen shape,
// ADR-005) - this proto message is a wire-format transcription, not a
// redesign. Candles/Position/Account are flattened to proto-friendly shapes;
// Config (map[string]interface{} in Go) is passed as a JSON-encoded string
// field, since arbitrary interface{} values have no natural proto mapping
// and the strategy config JSON is already a JSON blob at rest
// (StrategyConfiguration.Configuration) - no new serialization format is
// introduced, just passed through.
type Candle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Timeframe     string                 `protobuf:"bytes,2,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	OpenTimeUnix  int64                  `protobuf:"varint,3,opt,name=open_time_unix,json=openTimeUnix,proto3" json:"open_time_unix,omitempty"`
	Open          float64                `protobuf:"fixed64,4,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,5,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,6,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,7,opt,name=close,proto3" json:"close,omitempty"`
	Volume        float64                `protobuf:"fixed64,8,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candle) Reset() {
	*x = Candle{}
	mi := &file_strategy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candle) ProtoMessage() {}

func (x *Candle) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candle.ProtoReflect.Descriptor instead.
func (*Candle) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{0}
}

func (x *Candle) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Candle) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *Candle) GetOpenTimeUnix() int64 {
	if x != nil {
		return x.OpenTimeUnix
	}
	return 0
}

func (x *Candle) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Candle) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Candle) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Candle) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Candle) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type Position struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Symbol          string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	EntryPrice      float64                `protobuf:"fixed64,2,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	Quantity        float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	StopLossPrice   *float64               `protobuf:"fixed64,4,opt,name=stop_loss_price,json=stopLossPrice,proto3,oneof" json:"stop_loss_price,omitempty"`
	StopLossOrderId string                 `protobuf:"bytes,5,opt,name=stop_loss_order_id,json=stopLossOrderId,proto3" json:"stop_loss_order_id,omitempty"`
	OpenedAtUnix    int64                  `protobuf:"varint,6,opt,name=opened_at_unix,json=openedAtUnix,proto3" json:"opened_at_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_strategy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{1}
}

func (x *Position) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Position) GetEntryPrice() float64 {
	if x != nil {
		return x.EntryPrice
	}
	return 0
}

func (x *Position) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Position) GetStopLossPrice() float64 {
	if x != nil && x.StopLossPrice != nil {
		return *x.StopLossPrice
	}
	return 0
}

func (x *Position) GetStopLossOrderId() string {
	if x != nil {
		return x.StopLossOrderId
	}
	return ""
}

func (x *Position) GetOpenedAtUnix() int64 {
	if x != nil {
		return x.OpenedAtUnix
	}
	return 0
}

type StrategyContext struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Candles          []*Candle              `protobuf:"bytes,1,rep,name=candles,proto3" json:"candles,omitempty"`
	Position         *Position              `protobuf:"bytes,2,opt,name=position,proto3,oneof" json:"position,omitempty"`
	AccountAvailable float64                `protobuf:"fixed64,3,opt,name=account_available,json=accountAvailable,proto3" json:"account_available,omitempty"`
	ConfigJson       string                 `protobuf:"bytes,4,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"` // JSON-encoded map[string]interface{}
	Price            float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Timeframe        string                 `protobuf:"bytes,6,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	Symbol           string                 `protobuf:"bytes,7,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Mode             string                 `protobuf:"bytes,8,opt,name=mode,proto3" json:"mode,omitempty"` // ExecutionMode.String() - "backtest"|"dryrun"|"paper"|"live"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StrategyContext) Reset() {
	*x = StrategyContext{}
	mi := &file_strategy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyContext) ProtoMessage() {}

func (x *StrategyContext) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyContext.ProtoReflect.Descriptor instead.
func (*StrategyContext) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{2}
}

func (x *StrategyContext) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

func (x *StrategyContext) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *StrategyContext) GetAccountAvailable() float64 {
	if x != nil {
		return x.AccountAvailable
	}
	return 0
}

func (x *StrategyContext) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *StrategyContext) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StrategyContext) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *StrategyContext) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StrategyContext) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qty           float64                `protobuf:"fixed64,1,opt,name=qty,proto3" json:"qty,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_strategy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{3}
}

func (x *Order) GetQty() float64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *Order) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Signal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buy           *Order                 `protobuf:"bytes,1,opt,name=buy,proto3,oneof" json:"buy,omitempty"`
	Sell          *Order                 `protobuf:"bytes,2,opt,name=sell,proto3,oneof" json:"sell,omitempty"`
	StopLoss      *Order                 `protobuf:"bytes,3,opt,name=stop_loss,json=stopLoss,proto3,oneof" json:"stop_loss,omitempty"`
	TakeProfit    *Order                 `protobuf:"bytes,4,opt,name=take_profit,json=takeProfit,proto3,oneof" json:"take_profit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_strategy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{4}
}

func (x *Signal) GetBuy() *Order {
	if x != nil {
		return x.Buy
	}
	return nil
}

func (x *Signal) GetSell() *Order {
	if x != nil {
		return x.Sell
	}
	return nil
}

func (x *Signal) GetStopLoss() *Order {
	if x != nil {
		return x.StopLoss
	}
	return nil
}

func (x *Signal) GetTakeProfit() *Order {
	if x != nil {
		return x.TakeProfit
	}
	return nil
}

type BoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolResponse) Reset() {
	*x = BoolResponse{}
	mi := &file_strategy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolResponse) ProtoMessage() {}

func (x *BoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolResponse.ProtoReflect.Descriptor instead.
func (*BoolResponse) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{5}
}

func (x *BoolResponse) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signal        *Signal                `protobuf:"bytes,1,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_strategy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{6}
}

func (x *SignalResponse) GetSignal() *Signal {
	if x != nil {
		return x.Signal
	}
	return nil
}

type NullableSignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signal        *Signal                `protobuf:"bytes,1,opt,name=signal,proto3,oneof" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullableSignalResponse) Reset() {
	*x = NullableSignalResponse{}
	mi := &file_strategy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullableSignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableSignalResponse) ProtoMessage() {}

func (x *NullableSignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableSignalResponse.ProtoReflect.Descriptor instead.
func (*NullableSignalResponse) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{7}
}

func (x *NullableSignalResponse) GetSignal() *Signal {
	if x != nil {
		return x.Signal
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_strategy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{8}
}

type NameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameResponse) Reset() {
	*x = NameResponse{}
	mi := &file_strategy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameResponse) ProtoMessage() {}

func (x *NameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameResponse.ProtoReflect.Descriptor instead.
func (*NameResponse) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{9}
}

func (x *NameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_strategy_proto protoreflect.FileDescriptor

const file_strategy_proto_rawDesc = "" +
	"\n" +
	"\x0estrategy.proto\x12\bstrategy\"\xcc\x01\n" +
	"\x06Candle\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1c\n" +
	"\ttimeframe\x18\x02 \x01(\tR\ttimeframe\x12$\n" +
	"\x0eopen_time_unix\x18\x03 \x01(\x03R\fopenTimeUnix\x12\x12\n" +
	"\x04open\x18\x04 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x05 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x06 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\a \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\b \x01(\x01R\x06volume\"\xf3\x01\n" +
	"\bPosition\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1f\n" +
	"\ventry_price\x18\x02 \x01(\x01R\n" +
	"entryPrice\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\x12+\n" +
	"\x0fstop_loss_price\x18\x04 \x01(\x01H\x00R\rstopLossPrice\x88\x01\x01\x12+\n" +
	"\x12stop_loss_order_id\x18\x05 \x01(\tR\x0fstopLossOrderId\x12$\n" +
	"\x0eopened_at_unix\x18\x06 \x01(\x03R\fopenedAtUnixB\x12\n" +
	"\x10_stop_loss_price\"\xad\x02\n" +
	"\x0fStrategyContext\x12*\n" +
	"\acandles\x18\x01 \x03(\v2\x10.strategy.CandleR\acandles\x123\n" +
	"\bposition\x18\x02 \x01(\v2\x12.strategy.PositionH\x00R\bposition\x88\x01\x01\x12+\n" +
	"\x11account_available\x18\x03 \x01(\x01R\x10accountAvailable\x12\x1f\n" +
	"\vconfig_json\x18\x04 \x01(\tR\n" +
	"configJson\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1c\n" +
	"\ttimeframe\x18\x06 \x01(\tR\ttimeframe\x12\x16\n" +
	"\x06symbol\x18\a \x01(\tR\x06symbol\x12\x12\n" +
	"\x04mode\x18\b \x01(\tR\x04modeB\v\n" +
	"\t_position\"/\n" +
	"\x05Order\x12\x10\n" +
	"\x03qty\x18\x01 \x01(\x01R\x03qty\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\"\xf3\x01\n" +
	"\x06Signal\x12&\n" +
	"\x03buy\x18\x01 \x01(\v2\x0f.strategy.OrderH\x00R\x03buy\x88\x01\x01\x12(\n" +
	"\x04sell\x18\x02 \x01(\v2\x0f.strategy.OrderH\x01R\x04sell\x88\x01\x01\x121\n" +
	"\tstop_loss\x18\x03 \x01(\v2\x0f.strategy.OrderH\x02R\bstopLoss\x88\x01\x01\x125\n" +
	"\vtake_profit\x18\x04 \x01(\v2\x0f.strategy.OrderH\x03R\n" +
	"takeProfit\x88\x01\x01B\x06\n" +
	"\x04_buyB\a\n" +
	"\x05_sellB\f\n" +
	"\n" +
	"_stop_lossB\x0e\n" +
	"\f_take_profit\"$\n" +
	"\fBoolResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\":\n" +
	"\x0eSignalResponse\x12(\n" +
	"\x06signal\x18\x01 \x01(\v2\x10.strategy.SignalR\x06signal\"R\n" +
	"\x16NullableSignalResponse\x12-\n" +
	"\x06signal\x18\x01 \x01(\v2\x10.strategy.SignalH\x00R\x06signal\x88\x01\x01B\t\n" +
	"\a_signal\"\a\n" +
	"\x05Empty\"\"\n" +
	"\fNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xb2\x04\n" +
	"\n" +
	"MLStrategy\x12/\n" +
	"\x04Name\x12\x0f.strategy.Empty\x1a\x16.strategy.NameResponse\x124\n" +
	"\x06Before\x12\x19.strategy.StrategyContext\x1a\x0f.strategy.Empty\x12?\n" +
	"\n" +
	"ShouldLong\x12\x19.strategy.StrategyContext\x1a\x16.strategy.BoolResponse\x12=\n" +
	"\x06GoLong\x12\x19.strategy.StrategyContext\x1a\x18.strategy.SignalResponse\x12@\n" +
	"\vShouldShort\x12\x19.strategy.StrategyContext\x1a\x16.strategy.BoolResponse\x12>\n" +
	"\aGoShort\x12\x19.strategy.StrategyContext\x1a\x18.strategy.SignalResponse\x12M\n" +
	"\x0eUpdatePosition\x12\x19.strategy.StrategyContext\x1a .strategy.NullableSignalResponse\x123\n" +
	"\x05After\x12\x19.strategy.StrategyContext\x1a\x0f.strategy.Empty\x127\n" +
	"\tTerminate\x12\x19.strategy.StrategyContext\x1a\x0f.strategy.EmptyB'Z%go-trade-bot/internal/grpc/strategypbb\x06proto3"

var (
	file_strategy_proto_rawDescOnce sync.Once
	file_strategy_proto_rawDescData []byte
)

func file_strategy_proto_rawDescGZIP() []byte {
	file_strategy_proto_rawDescOnce.Do(func() {
		file_strategy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_strategy_proto_rawDesc), len(file_strategy_proto_rawDesc)))
	})
	return file_strategy_proto_rawDescData
}

var file_strategy_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_strategy_proto_goTypes = []any{
	(*Candle)(nil),                 // 0: strategy.Candle
	(*Position)(nil),               // 1: strategy.Position
	(*StrategyContext)(nil),        // 2: strategy.StrategyContext
	(*Order)(nil),                  // 3: strategy.Order
	(*Signal)(nil),                 // 4: strategy.Signal
	(*BoolResponse)(nil),           // 5: strategy.BoolResponse
	(*SignalResponse)(nil),         // 6: strategy.SignalResponse
	(*NullableSignalResponse)(nil), // 7: strategy.NullableSignalResponse
	(*Empty)(nil),                  // 8: strategy.Empty
	(*NameResponse)(nil),           // 9: strategy.NameResponse
}
var file_strategy_proto_depIdxs = []int32{
	0,  // 0: strategy.StrategyContext.candles:type_name -> strategy.Candle
	1,  // 1: strategy.StrategyContext.position:type_name -> strategy.Position
	3,  // 2: strategy.Signal.buy:type_name -> strategy.Order
	3,  // 3: strategy.Signal.sell:type_name -> strategy.Order
	3,  // 4: strategy.Signal.stop_loss:type_name -> strategy.Order
	3,  // 5: strategy.Signal.take_profit:type_name -> strategy.Order
	4,  // 6: strategy.SignalResponse.signal:type_name -> strategy.Signal
	4,  // 7: strategy.NullableSignalResponse.signal:type_name -> strategy.Signal
	8,  // 8: strategy.MLStrategy.Name:input_type -> strategy.Empty
	2,  // 9: strategy.MLStrategy.Before:input_type -> strategy.StrategyContext
	2,  // 10: strategy.MLStrategy.ShouldLong:input_type -> strategy.StrategyContext
	2,  // 11: strategy.MLStrategy.GoLong:input_type -> strategy.StrategyContext
	2,  // 12: strategy.MLStrategy.ShouldShort:input_type -> strategy.StrategyContext
	2,  // 13: strategy.MLStrategy.GoShort:input_type -> strategy.StrategyContext
	2,  // 14: strategy.MLStrategy.UpdatePosition:input_type -> strategy.StrategyContext
	2,  // 15: strategy.MLStrategy.After:input_type -> strategy.StrategyContext
	2,  // 16: strategy.MLStrategy.Terminate:input_type -> strategy.StrategyContext
	9,  // 17: strategy.MLStrategy.Name:output_type -> strategy.NameResponse
	8,  // 18: strategy.MLStrategy.Before:output_type -> strategy.Empty
	5,  // 19: strategy.MLStrategy.ShouldLong:output_type -> strategy.BoolResponse
	6,  // 20: strategy.MLStrategy.GoLong:output_type -> strategy.SignalResponse
	5,  // 21: strategy.MLStrategy.ShouldShort:output_type -> strategy.BoolResponse
	6,  // 22: strategy.MLStrategy.GoShort:output_type -> strategy.SignalResponse
	7,  // 23: strategy.MLStrategy.UpdatePosition:output_type -> strategy.NullableSignalResponse
	8,  // 24: strategy.MLStrategy.After:output_type -> strategy.Empty
	8,  // 25: strategy.MLStrategy.Terminate:output_type -> strategy.Empty
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_strategy_proto_init() }
func file_strategy_proto_init() {
	if File_strategy_proto != nil {
		return
	}
	file_strategy_proto_msgTypes[1].OneofWrappers = []any{}
	file_strategy_proto_msgTypes[2].OneofWrappers = []any{}
	file_strategy_proto_msgTypes[4].OneofWrappers = []any{}
	file_strategy_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_strategy_proto_rawDesc), len(file_strategy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_strategy_proto_goTypes,
		DependencyIndexes: file_strategy_proto_depIdxs,
		MessageInfos:      file_strategy_proto_msgTypes,
	}.Build()
	File_strategy_proto = out.File
	file_strategy_proto_goTypes = nil
	file_strategy_proto_depIdxs = nil
}
