// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: strategy.proto

package strategypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MLStrategy_Name_FullMethodName           = "/strategy.MLStrategy/Name"
	MLStrategy_Before_FullMethodName         = "/strategy.MLStrategy/Before"
	MLStrategy_ShouldLong_FullMethodName     = "/strategy.MLStrategy/ShouldLong"
	MLStrategy_GoLong_FullMethodName         = "/strategy.MLStrategy/GoLong"
	MLStrategy_ShouldShort_FullMethodName    = "/strategy.MLStrategy/ShouldShort"
	MLStrategy_GoShort_FullMethodName        = "/strategy.MLStrategy/GoShort"
	MLStrategy_UpdatePosition_FullMethodName = "/strategy.MLStrategy/UpdatePosition"
	MLStrategy_After_FullMethodName          = "/strategy.MLStrategy/After"
	MLStrategy_Terminate_FullMethodName      = "/strategy.MLStrategy/Terminate"
)

// MLStrategyClient is the client API for MLStrategy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// One RPC per Strategy hook - a direct 1:1 mapping, not a generic
// "call method X" RPC, so the .proto file itself documents the exact
// frozen contract a Python implementation must satisfy.
type MLStrategyClient interface {
	Name(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NameResponse, error)
	Before(ctx context.Context, in *StrategyContext, opts ...grpc.CallOption) (*Empty, error)
	ShouldLong(ctx context.Context, in *StrategyContext, opts ...grpc.CallOption) (*BoolResponse, error)
	GoLong(ctx context.Context, in *StrategyContext, opts ...grpc.CallOption) (*SignalResponse, error)
	ShouldShort(ctx context.Context, in *StrategyContext, opts ...grpc.CallOption) (*BoolResponse, error)
	GoShort(ctx context.Context, in *StrategyContext, opts ...grpc.CallOption) (*SignalResponse, error)
	UpdatePosition(ctx context.Context, in *StrategyContext, opts ...grpc.CallOption) (*NullableSignalResponse, error)
	After(ctx context.Context, in *StrategyContext, opts ...grpc.CallOption) (*Empty, error)
	Terminate(ctx context.Context, in *StrategyContext, opts ...grpc.CallOption) (*Empty, error)
}

type mLStrategyClient struct {
	cc grpc.ClientConnInterface
}

func NewMLStrategyClient(cc grpc.ClientConnInterface) MLStrategyClient {
	return &mLStrategyClient{cc}
}

func (c *mLStrategyClient) Name(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NameResponse)
	err := c.cc.Invoke(ctx, MLStrategy_Name_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLStrategyClient) Before(ctx context.Context, in *StrategyContext, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MLStrategy_Before_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLStrategyClient) ShouldLong(ctx context.Context, in *StrategyContext, opts ...grpc.CallOption) (*BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, MLStrategy_ShouldLong_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLStrategyClient) GoLong(ctx context.Context, in *StrategyContext, opts ...grpc.CallOption) (*SignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalResponse)
	err := c.cc.Invoke(ctx, MLStrategy_GoLong_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLStrategyClient) ShouldShort(ctx context.Context, in *StrategyContext, opts ...grpc.CallOption) (*BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, MLStrategy_ShouldShort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLStrategyClient) GoShort(ctx context.Context, in *StrategyContext, opts ...grpc.CallOption) (*SignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalResponse)
	err := c.cc.Invoke(ctx, MLStrategy_GoShort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLStrategyClient) UpdatePosition(ctx context.Context, in *StrategyContext, opts ...grpc.CallOption) (*NullableSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NullableSignalResponse)
	err := c.cc.Invoke(ctx, MLStrategy_UpdatePosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLStrategyClient) After(ctx context.Context, in *StrategyContext, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MLStrategy_After_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLStrategyClient) Terminate(ctx context.Context, in *StrategyContext, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MLStrategy_Terminate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MLStrategyServer is the server API for MLStrategy service.
// All implementations must embed UnimplementedMLStrategyServer
// for forward compatibility.
//
// One RPC per Strategy hook - a direct 1:1 mapping, not a generic
// "call method X" RPC, so the .proto file itself documents the exact
// frozen contract a Python implementation must satisfy.
type MLStrategyServer interface {
	Name(context.Context, *Empty) (*NameResponse, error)
	Before(context.Context, *StrategyContext) (*Empty, error)
	ShouldLong(context.Context, *StrategyContext) (*BoolResponse, error)
	GoLong(context.Context, *StrategyContext) (*SignalResponse, error)
	ShouldShort(context.Context, *StrategyContext) (*BoolResponse, error)
	GoShort(context.Context, *StrategyContext) (*SignalResponse, error)
	UpdatePosition(context.Context, *StrategyContext) (*NullableSignalResponse, error)
	After(context.Context, *StrategyContext) (*Empty, error)
	Terminate(context.Context, *StrategyContext) (*Empty, error)
	mustEmbedUnimplementedMLStrategyServer()
}

// UnimplementedMLStrategyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMLStrategyServer struct{}

func (UnimplementedMLStrategyServer) Name(context.Context, *Empty) (*NameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedMLStrategyServer) Before(context.Context, *StrategyContext) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Before not implemented")
}
func (UnimplementedMLStrategyServer) ShouldLong(context.Context, *StrategyContext) (*BoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShouldLong not implemented")
}
func (UnimplementedMLStrategyServer) GoLong(context.Context, *StrategyContext) (*SignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GoLong not implemented")
}
func (UnimplementedMLStrategyServer) ShouldShort(context.Context, *StrategyContext) (*BoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShouldShort not implemented")
}
func (UnimplementedMLStrategyServer) GoShort(context.Context, *StrategyContext) (*SignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GoShort not implemented")
}
func (UnimplementedMLStrategyServer) UpdatePosition(context.Context, *StrategyContext) (*NullableSignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePosition not implemented")
}
func (UnimplementedMLStrategyServer) After(context.Context, *StrategyContext) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method After not implemented")
}
func (UnimplementedMLStrategyServer) Terminate(context.Context, *StrategyContext) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Terminate not implemented")
}
func (UnimplementedMLStrategyServer) mustEmbedUnimplementedMLStrategyServer() {}
func (UnimplementedMLStrategyServer) testEmbeddedByValue()                    {}

// UnsafeMLStrategyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MLStrategyServer will
// result in compilation errors.
type UnsafeMLStrategyServer interface {
	mustEmbedUnimplementedMLStrategyServer()
}

func RegisterMLStrategyServer(s grpc.ServiceRegistrar, srv MLStrategyServer) {
	// If the following call panics, it indicates UnimplementedMLStrategyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MLStrategy_ServiceDesc, srv)
}

func _MLStrategy_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLStrategyServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLStrategy_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLStrategyServer).Name(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLStrategy_Before_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyContext)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLStrategyServer).Before(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLStrategy_Before_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLStrategyServer).Before(ctx, req.(*StrategyContext))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLStrategy_ShouldLong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyContext)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLStrategyServer).ShouldLong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLStrategy_ShouldLong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLStrategyServer).ShouldLong(ctx, req.(*StrategyContext))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLStrategy_GoLong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyContext)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLStrategyServer).GoLong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLStrategy_GoLong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLStrategyServer).GoLong(ctx, req.(*StrategyContext))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLStrategy_ShouldShort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyContext)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLStrategyServer).ShouldShort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLStrategy_ShouldShort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLStrategyServer).ShouldShort(ctx, req.(*StrategyContext))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLStrategy_GoShort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyContext)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLStrategyServer).GoShort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLStrategy_GoShort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLStrategyServer).GoShort(ctx, req.(*StrategyContext))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLStrategy_UpdatePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyContext)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLStrategyServer).UpdatePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLStrategy_UpdatePosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLStrategyServer).UpdatePosition(ctx, req.(*StrategyContext))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLStrategy_After_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyContext)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLStrategyServer).After(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLStrategy_After_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLStrategyServer).After(ctx, req.(*StrategyContext))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLStrategy_Terminate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyContext)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLStrategyServer).Terminate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLStrategy_Terminate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLStrategyServer).Terminate(ctx, req.(*StrategyContext))
	}
	return interceptor(ctx, in, info, handler)
}

// MLStrategy_ServiceDesc is the grpc.ServiceDesc for MLStrategy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MLStrategy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "strategy.MLStrategy",
	HandlerType: (*MLStrategyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Name",
			Handler:    _MLStrategy_Name_Handler,
		},
		{
			MethodName: "Before",
			Handler:    _MLStrategy_Before_Handler,
		},
		{
			MethodName: "ShouldLong",
			Handler:    _MLStrategy_ShouldLong_Handler,
		},
		{
			MethodName: "GoLong",
			Handler:    _MLStrategy_GoLong_Handler,
		},
		{
			MethodName: "ShouldShort",
			Handler:    _MLStrategy_ShouldShort_Handler,
		},
		{
			MethodName: "GoShort",
			Handler:    _MLStrategy_GoShort_Handler,
		},
		{
			MethodName: "UpdatePosition",
			Handler:    _MLStrategy_UpdatePosition_Handler,
		},
		{
			MethodName: "After",
			Handler:    _MLStrategy_After_Handler,
		},
		{
			MethodName: "Terminate",
			Handler:    _MLStrategy_Terminate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "strategy.proto",
}
